name: Automerge

on:
  pull_request:
    branches:
      - develop

jobs:
  auto-merge:
    if: contains(github.event.pull_request.user.login, 'dependabot')
    runs-on: ubuntu-latest
    steps:
      - name: Merge pull requests from dependabot
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          MERGE_LABELS: ''
          MERGE_METHOD: rebase
